"""GitHub integration endpoints for David AI.

Endpoints live under /api/github and are wired into the shared api_router.
All GitHub operations run server-side; the frontend never sees tokens,
private keys, or OAuth secrets.

Endpoints
---------
GET  /api/github/health                 Connection readiness (never exposes secrets)
GET  /api/github/connection             Current connection state + GitHub identity
POST /api/github/connect                Returns {authorize_url, state} for the owner
POST /api/github/connect/callback       Exchanges an OAuth code; stores token server-side
POST /api/github/disconnect             Clears the stored connection
GET  /api/github/repositories           All tracked repositories (optional ?project_id=)
GET  /api/github/repositories/{id}      Single tracked repository
POST /api/github/repositories           Create a new repository for a website project
POST /api/github/repositories/{id}/push Push generated files to the repository
POST /api/github/repositories/{id}/update Update tracked metadata (branch, deployment)
GET  /api/github/audit                  Recent GitHub audit events
"""

from __future__ import annotations

import logging
import secrets
from typing import Any

import time

from fastapi import APIRouter, Depends, HTTPException, Query
from fastapi.responses import HTMLResponse
from pydantic import BaseModel

from app.core.config import Settings, get_settings
from app.services.github_persistence import GitHubPersistence, audit_commit_created, audit_connected, audit_files_pushed, audit_initialized, audit_repository_created, audit_repository_updated
from app.services.github_service import (
    GitHubError,
    GitHubNotConfigured,
    GitHubService,
)
from app.services.supabase_service import SupabaseNotConfigured, SupabasePersistence

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/github", tags=["github"])

_pending_oauth_states: dict[str, float] = {}
_OAUTH_STATE_TTL_SECONDS = 600


def _expire_stale_oauth_states() -> None:
    """Drop connection states that have outlived the allowed round trip."""
    now = time.time()
    expired = [state for state, started in _pending_oauth_states.items() if now - started > _OAUTH_STATE_TTL_SECONDS]
    for state in expired:
        del _pending_oauth_states[state]


class RepoCreateRequest(BaseModel):
    topic: str
    project_id: str | None = None
    description: str = "Generated by David AI"
    private: bool = True


class RepoPushRequest(BaseModel):
    files: dict[str, str]
    branch: str | None = None
    message: str | None = None


class RepoUpdateRequest(BaseModel):
    last_commit_sha: str | None = None
    deployment_provider: str | None = None
    deployment_url: str | None = None
    deployment_status: str | None = None


def _get_settings() -> Settings:
    return get_settings()


def _github_service(settings: Settings) -> GitHubService:
    return GitHubService.from_settings(settings)


def _persistence(settings: Settings) -> GitHubPersistence | None:
    """Build the persistence layer; returns ``None`` when the database is
    not configured so routes can respond with a 503 instead of a 500."""
    try:
        return GitHubPersistence(SupabasePersistence(settings))
    except SupabaseNotConfigured:
        return None


def _github_error(exc: GitHubError, default_status: int = 502) -> HTTPException:
    if isinstance(exc, GitHubNotConfigured):
        return HTTPException(status_code=412, detail=str(exc))
    status = exc.status_code or default_status
    return HTTPException(status_code=status, detail={"error_code": exc.error_code, "message": str(exc), "retry_after": exc.retry_after})


def _safe_details(details: dict[str, Any] | None) -> dict[str, Any]:
    """Strip anything secret-shaped before returning it to the dashboard."""
    if not details:
        return {}
    out: dict[str, Any] = {}
    for key, value in details.items():
        lowered = str(key).lower()
        if any(secret in lowered for secret in ("token", "secret", "key", "password", "authorization", "private", "credential")):
            continue
        out[key] = value
    return out


@router.get("/health")
def github_health(settings: Settings = Depends(_get_settings)) -> dict[str, Any]:
    return GitHubService.from_settings(settings).health()


@router.get("/connection")
def github_connection(settings: Settings = Depends(_get_settings)) -> dict[str, Any]:
    service = _github_service(settings)
    if not service.is_configured:
        return {"connected": False, "configured": False, "github": None}
    try:
        user = service.get_authenticated_user()
        return {"connected": True, "configured": True, "github": user}
    except GitHubError:
        return {"connected": False, "configured": True, "github": None}


@router.post("/connect")
def github_connect(settings: Settings = Depends(_get_settings)) -> dict[str, Any]:
    """Start the Connect GitHub flow. Returns the authorization URL the
    owner's browser must visit. The state parameter is stored server-side
    for one round trip and then discarded."""
    service = _github_service(settings)
    try:
        _expire_stale_oauth_states()
        state = secrets.token_urlsafe(24)
        _pending_oauth_states[state] = time.time()
        url = service.oauth_authorize_url(state)
        return {"authorize_url": url, "state": state}
    except GitHubError as exc:
        raise _github_error(exc)


@router.get("/connect/callback")
def github_connect_callback_browser(code: str, state: str, settings: Settings = Depends(_get_settings)) -> HTMLResponse:
    """Browser entry point for the GitHub OAuth redirect. GitHub returns the
    owner here with ``code`` and ``state`` query parameters after approval.
    This route exchanges the code server-side (the access token never reaches
    the browser URL chain beyond the initial redirect), then hands the
    dashboard back to the owner via the window opener (popup flow) or by
    reloading the dashboard (normal tab flow)."""
    _expire_stale_oauth_states()
    body = (
        "<!doctype html>"
        "<html><head><meta charset=\"utf-8\">"
        "<title>David AI \u2014 GitHub</title>"
        "<style>body{background:#0a0a0f;color:#fff;font-family:sans-serif;display:grid;place-items:center;height:100vh;margin:0;}</style>"
        "</head><body><p>Finishing the GitHub connection&hellip;</p>"
        "<script>"
        f"fetch('/api/github/connect/callback',{{method:'POST',headers:{{'Content-Type':'application/json'}},body:JSON.stringify({{code:{json.dumps(code)},state:{json.dumps(state)}}})}})"
        ".then(r=>r.ok?r.json():Promise.reject(new Error('Connect failed')))"
        ".then(()=>{{"
        "if(window.opener&&!window.opener.closed){{window.opener.postMessage({{type:'github-connected'}},window.location.origin);window.close();}}"
        "else{{window.location.href='/dashboard';}}"
        "}}).catch(()=>{{window.location.href='/dashboard';}})"
        "</script></body></html>"
    )
    return HTMLResponse(body)


@router.post("/connect/callback")
def github_connect_callback(payload: dict[str, Any], settings: Settings = Depends(_get_settings)) -> dict[str, Any]:
    """Exchange an OAuth authorization code for a user token, store it
    server-side, and return only the GitHub identity."""
    _expire_stale_oauth_states()
    code = str(payload.get("code", "")).strip()
    state = str(payload.get("state", "")).strip()
    if not code:
        raise HTTPException(status_code=400, detail="Missing authorization code")
    if state not in _pending_oauth_states:
        raise HTTPException(status_code=400, detail="Unknown or expired connection state")
    del _pending_oauth_states[state]
    service = _github_service(settings)
    try:
        exchange = service.oauth_exchange_code(code)
    except GitHubError as exc:
        raise _github_error(exc)
    # Server-side persistence only. The token never travels to the frontend.
    # Render environment variables are the source of truth; a callback
    # stores the token for the current process lifetime in a guarded map.
    service._cached_token = exchange["oauth_access_token"]
    service._token_expires_at = time.time() + (3600 * 24 * 7)
    try:
        user = service.get_authenticated_user()
        persistence = _persistence(settings)
        if persistence is not None and persistence.is_available:
            audit_connected(persistence, user["login"])
        return {"connected": True, "github": user}
    except GitHubError as exc:
        raise _github_error(exc)


@router.post("/disconnect")
def github_disconnect(settings: Settings = Depends(_get_settings)) -> dict[str, Any]:
    service = _github_service(settings)
    service._cached_token = None
    service._token_expires_at = 0
    try:
        persistence = _persistence(settings)
        if persistence is not None and persistence.is_available:
            audit_disconnected(persistence)
    except Exception:  # noqa: BLE001 - audit failure must never break disconnect
        pass
    return {"connected": False}


@router.get("/repositories")
def list_tracked_repositories(
    project_id: str | None = Query(None),
    settings: Settings = Depends(_get_settings),
) -> list[dict[str, Any]]:
    persistence = _persistence(settings)
    if persistence is None or not persistence.is_available:
        raise HTTPException(status_code=503, detail="Database persistence is not available")
    return persistence.list_repositories(project_id=project_id)


@router.get("/repositories/{repository_id}")
def get_tracked_repository(repository_id: str, settings: Settings = Depends(_get_settings)) -> dict[str, Any]:
    persistence = _persistence(settings)
    record = persistence.get_repository(repository_id)
    if not record:
        raise HTTPException(status_code=404, detail="Tracked repository not found")
    return record


@router.post("/repositories")
def create_repository(payload: RepoCreateRequest, settings: Settings = Depends(_get_settings)) -> dict[str, Any]:
    topic = payload.topic.strip()
    if not topic:
        raise HTTPException(status_code=400, detail="topic is required")
    service = _github_service(settings)
    persistence = _persistence(settings)
    try:
        created = service.create_repository(topic, description=payload.description, private=payload.private)
        if persistence is not None and persistence.is_available:
            audit_repository_created(persistence, created, payload.project_id)
            record = persistence.create_repository_record(
                {
                    "repository_id": created["repository_id"],
                    "repository_name": created["repository_name"],
                    "repository_full_name": created["repository_full_name"],
                    "repository_owner": created["repository_owner"],
                    "repository_url": created["repository_url"],
                    "clone_url": created.get("clone_url"),
                    "default_branch": created["default_branch"],
                    "visibility": created["visibility"],
                    "project_id": payload.project_id,
                },
                project_id=payload.project_id,
            )
            created["id"] = record["id"]
            created["project_id"] = payload.project_id
        return created
    except GitHubError as exc:
        raise _github_error(exc)


@router.post("/repositories/{repository_id}/initialize")
def initialize_repository(repository_id: str, settings: Settings = Depends(_get_settings)) -> dict[str, Any]:
    persistence = _persistence(settings)
    record = persistence.get_repository(repository_id)
    if not record:
        raise HTTPException(status_code=404, detail="Tracked repository not found")
    service = _github_service(settings)
    try:
        result = service.initialize_repository(record["repository_full_name"], default_branch=record.get("default_branch", "main"))
        if persistence is not None and persistence.is_available:
            persistence.update_repository(
                repository_id,
                {
                    "default_branch": result["default_branch"],
                    "last_commit_sha": result["initial_commit_sha"],
                },
            )
            audit_initialized(persistence, record["repository_full_name"])
        return {**result, "repository_id": repository_id, "repository_url": record["repository_url"]}
    except GitHubError as exc:
        raise _github_error(exc)


@router.post("/repositories/{repository_id}/push")
def push_files(repository_id: str, payload: RepoPushRequest, settings: Settings = Depends(_get_settings)) -> dict[str, Any]:
    if not payload.files:
        raise HTTPException(status_code=400, detail="files is empty")
    total_bytes = sum(len(content.encode("utf-8")) for content in payload.files.values())
    if total_bytes > 25 * 1024 * 1024:
        raise HTTPException(status_code=413, detail="Push exceeds 25 MB limit")
    persistence = _persistence(settings)
    record = persistence.get_repository(repository_id)
    if not record:
        raise HTTPException(status_code=404, detail="Tracked repository not found")
    full_name = record["repository_full_name"]
    branch = payload.branch or record.get("default_branch", "main")
    message = payload.message or f"Push website files (David AI)"
    service = _github_service(settings)
    try:
        result = service.push_files(full_name, payload.files, branch=branch, message=message)
        if persistence is not None and persistence.is_available:
            persistence.update_repository(
                repository_id,
                {
                    "default_branch": result["branch"],
                    "last_commit_sha": result["last_commit_sha"],
                    "updated_at": __import__("datetime").datetime.now(__import__("datetime").timezone.utc).isoformat(),
                },
            )
            audit_files_pushed(persistence, full_name, len(payload.files), record.get("project_id"))
            if result["last_commit_sha"]:
                audit_commit_created(persistence, full_name, result["last_commit_sha"], record.get("project_id"))
        return {
            "repository_id": repository_id,
            "repository_full_name": full_name,
            "repository_url": record["repository_url"],
            "branch": result["branch"],
            "last_commit_sha": result["last_commit_sha"],
            "files_pushed": result["files_pushed"],
        }
    except GitHubError as exc:
        raise _github_error(exc)


@router.post("/repositories/{repository_id}/update")
def update_repository(repository_id: str, payload: RepoUpdateRequest, settings: Settings = Depends(_get_settings)) -> dict[str, Any]:
    persistence = _persistence(settings)
    record = persistence.get_repository(repository_id)
    if not record:
        raise HTTPException(status_code=404, detail="Tracked repository not found")
    patch: dict[str, Any] = {}
    if payload.last_commit_sha:
        patch["last_commit_sha"] = payload.last_commit_sha
    if payload.deployment_provider is not None:
        patch["deployment_provider"] = payload.deployment_provider
    if payload.deployment_url is not None:
        patch["deployment_url"] = payload.deployment_url
    if payload.deployment_status is not None:
        patch["deployment_status"] = payload.deployment_status
    if not patch:
        raise HTTPException(status_code=400, detail="No updatable fields provided")
    updated = persistence.update_repository(repository_id, patch)
    if updated is None:
        raise HTTPException(status_code=500, detail="Failed to update repository record")
    if persistence is not None and persistence.is_available:
        audit_repository_updated(persistence, record["repository_full_name"], "metadata update")
    return updated


@router.get("/audit")
def list_audit_events(limit: int = Query(50, ge=1, le=200), settings: Settings = Depends(_get_settings)) -> list[dict[str, Any]]:
    persistence = _persistence(settings)
    if persistence is None or not persistence.is_available:
        raise HTTPException(status_code=503, detail="Database persistence is not available")
    events = persistence.list_audit_events(limit=limit)
    return [{"id": e.get("id"), "event": e.get("event"), "details": _safe_details(e.get("details")), "created_at": e.get("created_at")} for e in events]
